### PR TITLE
Fix timestamp issue 

### PR DESCRIPTION
**Pull request by potapovDim**
https://github.com/allure-framework/allure-mocha/issues/44

### CODE REVIEW

**Comment by just-boris** [comment]
`allure-js-commons` package supposed to be very simple and lightweight. We expect, that package consumers provide data in already correct format and there is no need to do extra ckecks.

If you have more information how to reproduce the above mentioned issue, please share them there.

**Comment by potapovDim** [comment]
@just-boris end step was used like this  reporter.endStep('broken', \`${Date.now()} time\` )

**Comment by just-boris** [comment]
It is not the expected use case, that we considered.

The signature of the method is strict `endStep(status: string, timestamp: number)`.

What kind of use case do you have? Why could not prepare the number timestamp at your side?

**Comment by potapovDim** [comment]
@just-boris it was our fail, this pr was created as protection from a case like this because we spend some time before  an error was found in a code

**Comment by just-boris** [comment]
For the upcoming version there will be Typescript definitions that you can use to ensure that proper values are provided. But there are no actions for now.

**Pull request closed without merging**
