### PR TITLE
update fs-extra

### LINKED ISSUE #9: Could you update `graceful-fs` to eliminate `Please update to graceful-fs@^4.0.0 as soon as possible.` warning?
The warning message:
```
[91mnpm[0m[91m [0m[91mWARN[0m[91m [0m[91mdeprecated[0m[91m graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
```
after `npm ls graceful-fs` I got:
```
└─┬ jasmine-allure-reporter@1.0.0
  └─┬ allure-js-commons@1.1.4
    ├─┬ file-type@2.6.0
    │ └─┬ meow@3.7.0
    │   └─┬ read-pkg-up@1.0.1
    │     └─┬ read-pkg@1.1.0
    │       └─┬ load-json-file@1.1.0
    │         └── graceful-fs@4.1.4 
    └─┬ fs-extra@0.18.4
      └── graceful-fs@3.0.8 
```
Thank you for your help and support!

### PR DESCRIPTION
**Pull request by just-boris**
fixes https://github.com/allure-framework/allure-jasmine-plugin/issues/9

### CODE REVIEW

**Comment by ctapobep** [comment]
Why did you put a ranged version instead of fixed version? Versions always need to be fixed, otherwise the builds are not reproducible and that's risky in general. (hm.. I remember discussing this already)

**Comment by just-boris** [comment]
Sure. I am still thinking that patch version range is okay. For example, now I don't have to update mocha adapter, that update had been delivered automatically.

I expect, that in patch releases only contain bug fixes which are good to deliver them to people.

**Comment by ctapobep** [comment]
> For example, now I don't have to update mocha adapter, that update had been delivered automatically.

If there is nothing in dependency that harms the lib, why would you need to update its version? 

> I expect, that in patch releases only contain bug fixes which are good to deliver them to people.

You may expect it, but you cannot guarantee that. And it's your lib that's going to be blamed (for a good reason) if one of its dependencies breaks with new update.

**Comment by just-boris** [comment]
You are right, for example, libraries is Java-world usually follow that way, because it is much safer. 

Node.js libraries usually have flexible version range. For me, it is okay while library follows semver. I trust libraries by default until the first issue, and it working fine.

You can stick with your approach, and keep fixed version of libraries. But then you have to do updates manually and deal with deprecation warnings like this more often.

**Pull request merged**
